version: "3.8"
services:
  backend:
    build: ./api
    container_name: backend
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
  frontend:
    build: ./myblog
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true